2024-10-06 04:43:15 ERROR Traceback (most recent call last):
  File "E:\venv\ml\Lib\site-packages\wandb\cli\cli.py", line 108, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\venv\ml\Lib\site-packages\wandb\cli\cli.py", line 252, in login
    wandb.login(
  File "E:\venv\ml\Lib\site-packages\wandb\sdk\wandb_login.py", line 84, in login
    configured = _login(
                 ^^^^^^^
  File "E:\venv\ml\Lib\site-packages\wandb\sdk\wandb_login.py", line 340, in _login
    wlogin.prompt_api_key()
  File "E:\venv\ml\Lib\site-packages\wandb\sdk\wandb_login.py", line 277, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.UsageError: api_key not configured (no-tty). call wandb login [your_api_key]

2024-10-06 04:43:53 ERROR Traceback (most recent call last):
  File "E:\venv\ml\Lib\site-packages\wandb\cli\cli.py", line 108, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\venv\ml\Lib\site-packages\wandb\cli\cli.py", line 252, in login
    wandb.login(
  File "E:\venv\ml\Lib\site-packages\wandb\sdk\wandb_login.py", line 84, in login
    configured = _login(
                 ^^^^^^^
  File "E:\venv\ml\Lib\site-packages\wandb\sdk\wandb_login.py", line 340, in _login
    wlogin.prompt_api_key()
  File "E:\venv\ml\Lib\site-packages\wandb\sdk\wandb_login.py", line 277, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.UsageError: api_key not configured (no-tty). call wandb login [your_api_key]

